### ISSUE TITLE
Error Fixy Wixy

### ISSUE THREAD

**Issue by kvzs** [Gigamons/gigamons_api#1]
Hii~~

I fixie wixied the JSON-api fucksy wucksie!!! xpp

I repwaced the Prototypes.func wiff a more ~streamylined~ kawaii Pwototypiee.funkywunks object that make the JS go sooper dooper fast!! XD *starts twerking*

Can u pwease merge my pwull wequest senpai?!! UwU

**Comment by Mempler** [comment]
Ofciursw, plwese mak a pwull reqwest!

**Comment by kvzs** [comment]
no
